/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ToolsCategoryImport } from './routes/tools/$category'
import { Route as ToolsRandomThaiNameImport } from './routes/tools/random/thai-name'
import { Route as ToolsRandomNumberImport } from './routes/tools/random/number'
import { Route as ToolsRandomFoodImport } from './routes/tools/random/food'
import { Route as ToolsRandomEnglishNameImport } from './routes/tools/random/english-name'
import { Route as ToolsRandomColorImport } from './routes/tools/random/color'
import { Route as ToolsCalculateTdeeImport } from './routes/tools/calculate/tdee'
import { Route as ToolsCalculateBmrImport } from './routes/tools/calculate/bmr'
import { Route as ToolsCalculateBmiImport } from './routes/tools/calculate/bmi'
import { Route as ToolsCalculateAgeImport } from './routes/tools/calculate/age'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCategoryRoute = ToolsCategoryImport.update({
  id: '/tools/$category',
  path: '/tools/$category',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomThaiNameRoute = ToolsRandomThaiNameImport.update({
  id: '/tools/random/thai-name',
  path: '/tools/random/thai-name',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomNumberRoute = ToolsRandomNumberImport.update({
  id: '/tools/random/number',
  path: '/tools/random/number',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomFoodRoute = ToolsRandomFoodImport.update({
  id: '/tools/random/food',
  path: '/tools/random/food',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomEnglishNameRoute = ToolsRandomEnglishNameImport.update({
  id: '/tools/random/english-name',
  path: '/tools/random/english-name',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomColorRoute = ToolsRandomColorImport.update({
  id: '/tools/random/color',
  path: '/tools/random/color',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculateTdeeRoute = ToolsCalculateTdeeImport.update({
  id: '/tools/calculate/tdee',
  path: '/tools/calculate/tdee',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculateBmrRoute = ToolsCalculateBmrImport.update({
  id: '/tools/calculate/bmr',
  path: '/tools/calculate/bmr',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculateBmiRoute = ToolsCalculateBmiImport.update({
  id: '/tools/calculate/bmi',
  path: '/tools/calculate/bmi',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculateAgeRoute = ToolsCalculateAgeImport.update({
  id: '/tools/calculate/age',
  path: '/tools/calculate/age',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/$category': {
      id: '/tools/$category'
      path: '/tools/$category'
      fullPath: '/tools/$category'
      preLoaderRoute: typeof ToolsCategoryImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculate/age': {
      id: '/tools/calculate/age'
      path: '/tools/calculate/age'
      fullPath: '/tools/calculate/age'
      preLoaderRoute: typeof ToolsCalculateAgeImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculate/bmi': {
      id: '/tools/calculate/bmi'
      path: '/tools/calculate/bmi'
      fullPath: '/tools/calculate/bmi'
      preLoaderRoute: typeof ToolsCalculateBmiImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculate/bmr': {
      id: '/tools/calculate/bmr'
      path: '/tools/calculate/bmr'
      fullPath: '/tools/calculate/bmr'
      preLoaderRoute: typeof ToolsCalculateBmrImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculate/tdee': {
      id: '/tools/calculate/tdee'
      path: '/tools/calculate/tdee'
      fullPath: '/tools/calculate/tdee'
      preLoaderRoute: typeof ToolsCalculateTdeeImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/color': {
      id: '/tools/random/color'
      path: '/tools/random/color'
      fullPath: '/tools/random/color'
      preLoaderRoute: typeof ToolsRandomColorImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/english-name': {
      id: '/tools/random/english-name'
      path: '/tools/random/english-name'
      fullPath: '/tools/random/english-name'
      preLoaderRoute: typeof ToolsRandomEnglishNameImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/food': {
      id: '/tools/random/food'
      path: '/tools/random/food'
      fullPath: '/tools/random/food'
      preLoaderRoute: typeof ToolsRandomFoodImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/number': {
      id: '/tools/random/number'
      path: '/tools/random/number'
      fullPath: '/tools/random/number'
      preLoaderRoute: typeof ToolsRandomNumberImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/thai-name': {
      id: '/tools/random/thai-name'
      path: '/tools/random/thai-name'
      fullPath: '/tools/random/thai-name'
      preLoaderRoute: typeof ToolsRandomThaiNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/tools/calculate/age': typeof ToolsCalculateAgeRoute
  '/tools/calculate/bmi': typeof ToolsCalculateBmiRoute
  '/tools/calculate/bmr': typeof ToolsCalculateBmrRoute
  '/tools/calculate/tdee': typeof ToolsCalculateTdeeRoute
  '/tools/random/color': typeof ToolsRandomColorRoute
  '/tools/random/english-name': typeof ToolsRandomEnglishNameRoute
  '/tools/random/food': typeof ToolsRandomFoodRoute
  '/tools/random/number': typeof ToolsRandomNumberRoute
  '/tools/random/thai-name': typeof ToolsRandomThaiNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/tools/calculate/age': typeof ToolsCalculateAgeRoute
  '/tools/calculate/bmi': typeof ToolsCalculateBmiRoute
  '/tools/calculate/bmr': typeof ToolsCalculateBmrRoute
  '/tools/calculate/tdee': typeof ToolsCalculateTdeeRoute
  '/tools/random/color': typeof ToolsRandomColorRoute
  '/tools/random/english-name': typeof ToolsRandomEnglishNameRoute
  '/tools/random/food': typeof ToolsRandomFoodRoute
  '/tools/random/number': typeof ToolsRandomNumberRoute
  '/tools/random/thai-name': typeof ToolsRandomThaiNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/tools/calculate/age': typeof ToolsCalculateAgeRoute
  '/tools/calculate/bmi': typeof ToolsCalculateBmiRoute
  '/tools/calculate/bmr': typeof ToolsCalculateBmrRoute
  '/tools/calculate/tdee': typeof ToolsCalculateTdeeRoute
  '/tools/random/color': typeof ToolsRandomColorRoute
  '/tools/random/english-name': typeof ToolsRandomEnglishNameRoute
  '/tools/random/food': typeof ToolsRandomFoodRoute
  '/tools/random/number': typeof ToolsRandomNumberRoute
  '/tools/random/thai-name': typeof ToolsRandomThaiNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/$category'
    | '/tools/calculate/age'
    | '/tools/calculate/bmi'
    | '/tools/calculate/bmr'
    | '/tools/calculate/tdee'
    | '/tools/random/color'
    | '/tools/random/english-name'
    | '/tools/random/food'
    | '/tools/random/number'
    | '/tools/random/thai-name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/$category'
    | '/tools/calculate/age'
    | '/tools/calculate/bmi'
    | '/tools/calculate/bmr'
    | '/tools/calculate/tdee'
    | '/tools/random/color'
    | '/tools/random/english-name'
    | '/tools/random/food'
    | '/tools/random/number'
    | '/tools/random/thai-name'
  id:
    | '__root__'
    | '/'
    | '/tools/$category'
    | '/tools/calculate/age'
    | '/tools/calculate/bmi'
    | '/tools/calculate/bmr'
    | '/tools/calculate/tdee'
    | '/tools/random/color'
    | '/tools/random/english-name'
    | '/tools/random/food'
    | '/tools/random/number'
    | '/tools/random/thai-name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsCategoryRoute: typeof ToolsCategoryRoute
  ToolsCalculateAgeRoute: typeof ToolsCalculateAgeRoute
  ToolsCalculateBmiRoute: typeof ToolsCalculateBmiRoute
  ToolsCalculateBmrRoute: typeof ToolsCalculateBmrRoute
  ToolsCalculateTdeeRoute: typeof ToolsCalculateTdeeRoute
  ToolsRandomColorRoute: typeof ToolsRandomColorRoute
  ToolsRandomEnglishNameRoute: typeof ToolsRandomEnglishNameRoute
  ToolsRandomFoodRoute: typeof ToolsRandomFoodRoute
  ToolsRandomNumberRoute: typeof ToolsRandomNumberRoute
  ToolsRandomThaiNameRoute: typeof ToolsRandomThaiNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsCategoryRoute: ToolsCategoryRoute,
  ToolsCalculateAgeRoute: ToolsCalculateAgeRoute,
  ToolsCalculateBmiRoute: ToolsCalculateBmiRoute,
  ToolsCalculateBmrRoute: ToolsCalculateBmrRoute,
  ToolsCalculateTdeeRoute: ToolsCalculateTdeeRoute,
  ToolsRandomColorRoute: ToolsRandomColorRoute,
  ToolsRandomEnglishNameRoute: ToolsRandomEnglishNameRoute,
  ToolsRandomFoodRoute: ToolsRandomFoodRoute,
  ToolsRandomNumberRoute: ToolsRandomNumberRoute,
  ToolsRandomThaiNameRoute: ToolsRandomThaiNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tools/$category",
        "/tools/calculate/age",
        "/tools/calculate/bmi",
        "/tools/calculate/bmr",
        "/tools/calculate/tdee",
        "/tools/random/color",
        "/tools/random/english-name",
        "/tools/random/food",
        "/tools/random/number",
        "/tools/random/thai-name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tools/$category": {
      "filePath": "tools/$category.tsx"
    },
    "/tools/calculate/age": {
      "filePath": "tools/calculate/age.tsx"
    },
    "/tools/calculate/bmi": {
      "filePath": "tools/calculate/bmi.tsx"
    },
    "/tools/calculate/bmr": {
      "filePath": "tools/calculate/bmr.tsx"
    },
    "/tools/calculate/tdee": {
      "filePath": "tools/calculate/tdee.tsx"
    },
    "/tools/random/color": {
      "filePath": "tools/random/color.tsx"
    },
    "/tools/random/english-name": {
      "filePath": "tools/random/english-name.tsx"
    },
    "/tools/random/food": {
      "filePath": "tools/random/food.tsx"
    },
    "/tools/random/number": {
      "filePath": "tools/random/number.tsx"
    },
    "/tools/random/thai-name": {
      "filePath": "tools/random/thai-name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
