/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ToolsCategoryImport } from './routes/tools/$category'
import { Route as ToolsRandomThaiNameImport } from './routes/tools/random/thai-name'
import { Route as ToolsRandomNumberImport } from './routes/tools/random/number'
import { Route as ToolsRandomEnglishNameImport } from './routes/tools/random/english-name'
import { Route as ToolsColorsRandomImport } from './routes/tools/colors/random'
import { Route as ToolsCalculatorsTdeeImport } from './routes/tools/calculators/tdee'
import { Route as ToolsCalculatorsBmrImport } from './routes/tools/calculators/bmr'
import { Route as ToolsCalculatorsBmiImport } from './routes/tools/calculators/bmi'
import { Route as ToolsCalculatorsAgeImport } from './routes/tools/calculators/age'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCategoryRoute = ToolsCategoryImport.update({
  id: '/tools/$category',
  path: '/tools/$category',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomThaiNameRoute = ToolsRandomThaiNameImport.update({
  id: '/tools/random/thai-name',
  path: '/tools/random/thai-name',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomNumberRoute = ToolsRandomNumberImport.update({
  id: '/tools/random/number',
  path: '/tools/random/number',
  getParentRoute: () => rootRoute,
} as any)

const ToolsRandomEnglishNameRoute = ToolsRandomEnglishNameImport.update({
  id: '/tools/random/english-name',
  path: '/tools/random/english-name',
  getParentRoute: () => rootRoute,
} as any)

const ToolsColorsRandomRoute = ToolsColorsRandomImport.update({
  id: '/tools/colors/random',
  path: '/tools/colors/random',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsTdeeRoute = ToolsCalculatorsTdeeImport.update({
  id: '/tools/calculators/tdee',
  path: '/tools/calculators/tdee',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsBmrRoute = ToolsCalculatorsBmrImport.update({
  id: '/tools/calculators/bmr',
  path: '/tools/calculators/bmr',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsBmiRoute = ToolsCalculatorsBmiImport.update({
  id: '/tools/calculators/bmi',
  path: '/tools/calculators/bmi',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsAgeRoute = ToolsCalculatorsAgeImport.update({
  id: '/tools/calculators/age',
  path: '/tools/calculators/age',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/$category': {
      id: '/tools/$category'
      path: '/tools/$category'
      fullPath: '/tools/$category'
      preLoaderRoute: typeof ToolsCategoryImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/age': {
      id: '/tools/calculators/age'
      path: '/tools/calculators/age'
      fullPath: '/tools/calculators/age'
      preLoaderRoute: typeof ToolsCalculatorsAgeImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/bmi': {
      id: '/tools/calculators/bmi'
      path: '/tools/calculators/bmi'
      fullPath: '/tools/calculators/bmi'
      preLoaderRoute: typeof ToolsCalculatorsBmiImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/bmr': {
      id: '/tools/calculators/bmr'
      path: '/tools/calculators/bmr'
      fullPath: '/tools/calculators/bmr'
      preLoaderRoute: typeof ToolsCalculatorsBmrImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/tdee': {
      id: '/tools/calculators/tdee'
      path: '/tools/calculators/tdee'
      fullPath: '/tools/calculators/tdee'
      preLoaderRoute: typeof ToolsCalculatorsTdeeImport
      parentRoute: typeof rootRoute
    }
    '/tools/colors/random': {
      id: '/tools/colors/random'
      path: '/tools/colors/random'
      fullPath: '/tools/colors/random'
      preLoaderRoute: typeof ToolsColorsRandomImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/english-name': {
      id: '/tools/random/english-name'
      path: '/tools/random/english-name'
      fullPath: '/tools/random/english-name'
      preLoaderRoute: typeof ToolsRandomEnglishNameImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/number': {
      id: '/tools/random/number'
      path: '/tools/random/number'
      fullPath: '/tools/random/number'
      preLoaderRoute: typeof ToolsRandomNumberImport
      parentRoute: typeof rootRoute
    }
    '/tools/random/thai-name': {
      id: '/tools/random/thai-name'
      path: '/tools/random/thai-name'
      fullPath: '/tools/random/thai-name'
      preLoaderRoute: typeof ToolsRandomThaiNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/tools/calculators/age': typeof ToolsCalculatorsAgeRoute
  '/tools/calculators/bmi': typeof ToolsCalculatorsBmiRoute
  '/tools/calculators/bmr': typeof ToolsCalculatorsBmrRoute
  '/tools/calculators/tdee': typeof ToolsCalculatorsTdeeRoute
  '/tools/colors/random': typeof ToolsColorsRandomRoute
  '/tools/random/english-name': typeof ToolsRandomEnglishNameRoute
  '/tools/random/number': typeof ToolsRandomNumberRoute
  '/tools/random/thai-name': typeof ToolsRandomThaiNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/tools/calculators/age': typeof ToolsCalculatorsAgeRoute
  '/tools/calculators/bmi': typeof ToolsCalculatorsBmiRoute
  '/tools/calculators/bmr': typeof ToolsCalculatorsBmrRoute
  '/tools/calculators/tdee': typeof ToolsCalculatorsTdeeRoute
  '/tools/colors/random': typeof ToolsColorsRandomRoute
  '/tools/random/english-name': typeof ToolsRandomEnglishNameRoute
  '/tools/random/number': typeof ToolsRandomNumberRoute
  '/tools/random/thai-name': typeof ToolsRandomThaiNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tools/$category': typeof ToolsCategoryRoute
  '/tools/calculators/age': typeof ToolsCalculatorsAgeRoute
  '/tools/calculators/bmi': typeof ToolsCalculatorsBmiRoute
  '/tools/calculators/bmr': typeof ToolsCalculatorsBmrRoute
  '/tools/calculators/tdee': typeof ToolsCalculatorsTdeeRoute
  '/tools/colors/random': typeof ToolsColorsRandomRoute
  '/tools/random/english-name': typeof ToolsRandomEnglishNameRoute
  '/tools/random/number': typeof ToolsRandomNumberRoute
  '/tools/random/thai-name': typeof ToolsRandomThaiNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/$category'
    | '/tools/calculators/age'
    | '/tools/calculators/bmi'
    | '/tools/calculators/bmr'
    | '/tools/calculators/tdee'
    | '/tools/colors/random'
    | '/tools/random/english-name'
    | '/tools/random/number'
    | '/tools/random/thai-name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/$category'
    | '/tools/calculators/age'
    | '/tools/calculators/bmi'
    | '/tools/calculators/bmr'
    | '/tools/calculators/tdee'
    | '/tools/colors/random'
    | '/tools/random/english-name'
    | '/tools/random/number'
    | '/tools/random/thai-name'
  id:
    | '__root__'
    | '/'
    | '/tools/$category'
    | '/tools/calculators/age'
    | '/tools/calculators/bmi'
    | '/tools/calculators/bmr'
    | '/tools/calculators/tdee'
    | '/tools/colors/random'
    | '/tools/random/english-name'
    | '/tools/random/number'
    | '/tools/random/thai-name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsCategoryRoute: typeof ToolsCategoryRoute
  ToolsCalculatorsAgeRoute: typeof ToolsCalculatorsAgeRoute
  ToolsCalculatorsBmiRoute: typeof ToolsCalculatorsBmiRoute
  ToolsCalculatorsBmrRoute: typeof ToolsCalculatorsBmrRoute
  ToolsCalculatorsTdeeRoute: typeof ToolsCalculatorsTdeeRoute
  ToolsColorsRandomRoute: typeof ToolsColorsRandomRoute
  ToolsRandomEnglishNameRoute: typeof ToolsRandomEnglishNameRoute
  ToolsRandomNumberRoute: typeof ToolsRandomNumberRoute
  ToolsRandomThaiNameRoute: typeof ToolsRandomThaiNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsCategoryRoute: ToolsCategoryRoute,
  ToolsCalculatorsAgeRoute: ToolsCalculatorsAgeRoute,
  ToolsCalculatorsBmiRoute: ToolsCalculatorsBmiRoute,
  ToolsCalculatorsBmrRoute: ToolsCalculatorsBmrRoute,
  ToolsCalculatorsTdeeRoute: ToolsCalculatorsTdeeRoute,
  ToolsColorsRandomRoute: ToolsColorsRandomRoute,
  ToolsRandomEnglishNameRoute: ToolsRandomEnglishNameRoute,
  ToolsRandomNumberRoute: ToolsRandomNumberRoute,
  ToolsRandomThaiNameRoute: ToolsRandomThaiNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tools/$category",
        "/tools/calculators/age",
        "/tools/calculators/bmi",
        "/tools/calculators/bmr",
        "/tools/calculators/tdee",
        "/tools/colors/random",
        "/tools/random/english-name",
        "/tools/random/number",
        "/tools/random/thai-name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tools/$category": {
      "filePath": "tools/$category.tsx"
    },
    "/tools/calculators/age": {
      "filePath": "tools/calculators/age.tsx"
    },
    "/tools/calculators/bmi": {
      "filePath": "tools/calculators/bmi.tsx"
    },
    "/tools/calculators/bmr": {
      "filePath": "tools/calculators/bmr.tsx"
    },
    "/tools/calculators/tdee": {
      "filePath": "tools/calculators/tdee.tsx"
    },
    "/tools/colors/random": {
      "filePath": "tools/colors/random.tsx"
    },
    "/tools/random/english-name": {
      "filePath": "tools/random/english-name.tsx"
    },
    "/tools/random/number": {
      "filePath": "tools/random/number.tsx"
    },
    "/tools/random/thai-name": {
      "filePath": "tools/random/thai-name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
