import { Mars, Venus } from "lucide-react";

export const GENDERS = [
  {
    value: "male",
    name: "ชาย",
    icon: <Mars size={16} />,
  },
  {
    value: "female",
    name: "หญิง",
    icon: <Venus size={16} />,
  },
] as const;

interface Category {
  name: string;
  url: string;
  items: {
    title: string;
    url: string;
    description: string;
  }[];
}

export const TOOL_CATEGORIES: Category[] = [
  {
    name: "เครื่องสุ่ม",
    url: "/tools/random",
    items: [
      {
        title: "สุ่มตัวเลข",
        url: "/tools/random/number",
        description:
          "สุ่มตัวเลขในช่วงที่คุณกำหนด เหมาะสำหรับจับฉลาก เล่นเกม หรือเลือกเลขแบบสุ่มง่าย ๆ",
      },
      {
        title: "สุ่มชื่อไทย",
        url: "/tools/random/thai-name",
        description: "สุ่มชื่อไทยแบบง่ายๆ ใช้ได้ทันที ไม่ต้องคิดเอง",
      },
    ],
  },
  {
    name: "เครื่องคำนวณ",
    url: "/tools/calculators",
    items: [
      {
        title: "คำนวณดัชนีมวลกาย (BMI)",
        url: "/tools/calculators/bmi",
        description: "เช็กสุขภาพคร่าว ๆ ด้วยค่าดัชนีมวลกายของคุณ",
      },
      {
        title: "คำนวณการเผาผลาญพลังงาน (BMR)",
        url: "/tools/calculators/bmr",
        description: "รู้ว่าร่างกายคุณต้องใช้พลังงานพื้นฐานเท่าไรในแต่ละวัน",
      },
      {
        title: "คำนวณพลังงานต่อวัน (TDEE)",
        url: "/tools/calculators/tdee",
        description:
          "ดูว่าคุณควรได้รับแคลอรี่ต่อวันเท่าไหร่เมื่อรวมกิจกรรมต่าง ๆ",
      },
    ],
  },
];

export const PERSON_NAMES = {
  maleNames: [
    { th: "กฤต", en: "Krit" },
    { th: "กฤติพงศ์", en: "Kritiphong" },
    { th: "กฤษฎา", en: "Kritsada" },
    { th: "กฤษณ์", en: "Krit" },
    { th: "กันตพงศ์", en: "Kantapong" },
    { th: "กิตติ", en: "Kitti" },
    { th: "กิตติศักดิ์", en: "Kittisak" },
    { th: "ก้องภพ", en: "Kongphop" },
    { th: "คมกริช", en: "Komkrit" },
    { th: "คมสันต์", en: "Khomsan" },
    { th: "ครรชิต", en: "Kharachit" },
    { th: "คำรณ", en: "Khamron" },
    { th: "จตุภัทร", en: "Chatuphat" },
    { th: "จรัล", en: "Charan" },
    { th: "จารุวัฒน์", en: "Charuwat" },
    { th: "จิรายุ", en: "Jirayu" },
    { th: "จิรายุทธ", en: "Jirayut" },
    { th: "ฉันทพล", en: "Chanthaphon" },
    { th: "ชนกันต์", en: "Chonakan" },
    { th: "ชนะศึก", en: "Chanasuek" },
    { th: "ชัชชัย", en: "Chatchai" },
    { th: "ชัชวาล", en: "Chatchawan" },
    { th: "ชัยณรงค์", en: "Chainarong" },
    { th: "ชัยวุฒิ", en: "Chaiwut" },
    { th: "ชาญชัย", en: "Charnchai" },
    { th: "ชานนท์", en: "Chanon" },
    { th: "ฐิติพงศ์", en: "Thitiphong" },
    { th: "ณรงค์", en: "Narong" },
    { th: "ณัฏฐพล", en: "Natthaphon" },
    { th: "ณัฐพงศ์", en: "Natthaphong" },
    { th: "ดนัย", en: "Danai" },
    { th: "ดุลยศักดิ์", en: "Dulyasak" },
    { th: "ตรีภพ", en: "Tripop" },
    { th: "ติณณภพ", en: "Tinnapop" },
    { th: "ทวีเดช", en: "Thawidet" },
    { th: "ธงชัย", en: "Thongchai" },
    { th: "ธนกร", en: "Thanakon" },
    { th: "ธนกฤต", en: "Thanakrit" },
    { th: "ธนภัทร", en: "Thanaphat" },
    { th: "ธนศักดิ์", en: "Thanasak" },
    { th: "ธนโชติ", en: "Thanachot" },
    { th: "ธวัชชัย", en: "Thawatchai" },
    { th: "ธีรพล", en: "Theeraphon" },
    { th: "นพเดช", en: "Noppadet" },
    { th: "นรวุฒิ", en: "Narawut" },
    { th: "บรรพต", en: "Banphot" },
    { th: "บวรชัย", en: "Bowonchai" },
    { th: "บุญฤทธิ์", en: "Boonrit" },
    { th: "บุรินทร์", en: "Burin" },
    { th: "ปกรณ์", en: "Pakorn" },
    { th: "ปรัชญา", en: "Pratchaya" },
    { th: "ปิติ", en: "Piti" },
    { th: "พงศ์เดช", en: "Phongdet" },
    { th: "พลวัต", en: "Phonlawat" },
    { th: "พิพัฒน์", en: "Piphat" },
    { th: "พิสิษฐ์", en: "Phisit" },
    { th: "พีรพล", en: "Peeraphon" },
    { th: "ภัทร", en: "Phat" },
    { th: "ภากร", en: "Phakon" },
    { th: "ภาณุพงศ์", en: "Phanuphong" },
    { th: "ภูมิ", en: "Phum" },
    { th: "ภูริช", en: "Phurich" },
    { th: "มงคล", en: "Mongkhon" },
    { th: "มนุญศักดิ์", en: "Manunsak" },
    { th: "ยุทธการ", en: "Yutthakan" },
    { th: "วรพจน์", en: "Woraphot" },
    { th: "วรพล", en: "Woraphon" },
    { th: "วรเทพ", en: "Worathep" },
    { th: "วัชรพล", en: "Watcharaphon" },
    { th: "วิทวัส", en: "Witthawat" },
    { th: "วิบูลย์", en: "Wibun" },
    { th: "วุฒิชัย", en: "Wutthichai" },
    { th: "ศักดา", en: "Sakda" },
    { th: "ศุภณัฐ", en: "Suphanat" },
    { th: "สมชาย", en: "Somchai" },
    { th: "สมศักดิ์", en: "Somsak" },
    { th: "สิทธิเดช", en: "Sitthidet" },
    { th: "สุทธินันท์", en: "Sutthinan" },
    { th: "สุบรรณ", en: "Suban" },
    { th: "สุเมธ", en: "Sumet" },
    { th: "อดิเทพ", en: "Adithep" },
    { th: "อนุชิต", en: "Anuchit" },
    { th: "อภิคม", en: "Aphikom" },
    { th: "อภิชาติ", en: "Apichat" },
    { th: "อัครชัย", en: "Akkharachai" },
    { th: "อาณัติ", en: "Anat" },
    { th: "อานนท์", en: "Anon" },
    { th: "อารักษ์", en: "Arak" },
    { th: "อิทธิชัย", en: "Itthichai" },
    { th: "เกริกไกร", en: "Kerkkrai" },
    { th: "เจตพล", en: "Jetphon" },
    { th: "เจษฎา", en: "Jetsada" },
    { th: "เด่นภูมิ", en: "Denphum" },
    { th: "เตชินท์", en: "Techin" },
    { th: "เผด็จ", en: "Phadet" },
    { th: "เมธัส", en: "Methas" },
    { th: "เรืองโรจน์", en: "Rueangrot" },
    { th: "เอกภพ", en: "Ekkaphop" },
    { th: "โกเมน", en: "Komen" },
    { th: "โฆษิต", en: "Khosit" },
    { th: "โอภาส", en: "Ophas" },
    { th: "ไชยวัฒน์", en: "Chaiwat" },
    { th: "ไตรภพ", en: "Traiphop" },
    { th: "ไพศาล", en: "Paisan" },
  ],
  maleNicknames: [
    { th: "กล้า", en: "Kla" },
    { th: "ก้อง", en: "Kong" },
    { th: "กัปตัน", en: "Captain" },
    { th: "เคน", en: "Ken" },
    { th: "คิว", en: "Q" },
    { th: "คิง", en: "King" },
    { th: "เค", en: "K" },
    { th: "จุก", en: "Chuk" },
    { th: "โจ", en: "Joe" },
    { th: "โจ้", en: "Joe" },
    { th: "แจ๊ค", en: "Jack" },
    { th: "เจมส์", en: "James" },
    { th: "จุ้ย", en: "Chui" },
    { th: "ชาญ", en: "Chan" },
    { th: "ช้าง", en: "Chang" },
    { th: "ชัย", en: "Chai" },
    { th: "โชค", en: "Chok" },
    { th: "แซม", en: "Sam" },
    { th: "โด่ง", en: "Dong" },
    { th: "เดช", en: "Det" },
    { th: "ดอน", en: "Don" },
    { th: "แดน", en: "Dan" },
    { th: "โดม", en: "Dome" },
    { th: "ตี๋", en: "Tee" },
    { th: "ต่อ", en: "Tor" },
    { th: "ตั้ม", en: "Tum" },
    { th: "เต้นท์", en: "Tent" },
    { th: "ตุ้ย", en: "Tui" },
    { th: "เต้", en: "Tae" },
    { th: "ตังกวย", en: "Tangkuay" },
    { th: "เทพ", en: "Thep" },
    { th: "ทัศน์", en: "That" },
    { th: "ท็อป", en: "Top" },
    { th: "นนท์", en: "Non" },
    { th: "นัท", en: "Nat" },
    { th: "บิ๊ก", en: "Big" },
    { th: "ไผ่", en: "Phai" },
    { th: "บูม", en: "Boom" },
    { th: "โบ๊ต", en: "Boat" },
    { th: "เปรม", en: "Prem" },
    { th: "โปเต้", en: "Potato" },
    { th: "โปรด", en: "Prode" },
    { th: "โป้ง", en: "Pong" },
    { th: "ป่าน", en: "Paan" },
    { th: "ปุ่น", en: "Pun" },
    { th: "พอล", en: "Paul" },
    { th: "เพชร", en: "Phet" },
    { th: "ภาค", en: "Phak" },
    { th: "ฟอร์ด", en: "Ford" },
    { th: "ฟิล์ม", en: "Film" },
    { th: "ภูมิ", en: "Phum" },
    { th: "แมน", en: "Man" },
    { th: "เมฆ", en: "Mek" },
    { th: "เม่น", en: "Men" },
    { th: "มาร์ค", en: "Mark" },
    { th: "ยอด", en: "Yot" },
    { th: "โรม", en: "Rome" },
    { th: "เรย์", en: "Ray" },
    { th: "ลีซอ", en: "Lee Saw" },
    { th: "ว่าน", en: "Wan" },
    { th: "วิน", en: "Win" },
    { th: "วัฒน์", en: "Wat" },
    { th: "วิทย์", en: "Wit" },
    { th: "ศร", en: "Son" },
    { th: "ศักดิ์", en: "Sak" },
    { th: "เสือ", en: "Suea" },
    { th: "ใหญ่", en: "Yai" },
    { th: "โอ", en: "O" },
    { th: "แอ๊ด", en: "Aed" },
    { th: "อาร์ต", en: "Art" },
    { th: "โอ๊ต", en: "Oat" },
    { th: "เอก", en: "Ek" },
    { th: "อาร์ม", en: "Arm" },
  ],
  femaleNames: [
    { th: "กชวรรณ", en: "Kotchawan" },
    { th: "กนกกาญจน์", en: "Kanokkan" },
    { th: "กนกทิพย์", en: "Kanokthip" },
    { th: "กนกพรรณ", en: "Kanokphan" },
    { th: "กนกรัตน์", en: "Kanokrat" },
    { th: "กมลฉัตร", en: "Kamonchat" },
    { th: "กมลชนก", en: "Kamonchanok" },
    { th: "กมลทิพย์", en: "Kamonthip" },
    { th: "กมลรัตน์", en: "Kamonrat" },
    { th: "กมลวรรณ", en: "Kamonwan" },
    { th: "กมลา", en: "Kamala" },
    { th: "กรกนก", en: "Kornkanok" },
    { th: "กรกมล", en: "Kornkamon" },
    { th: "กรรณิกา", en: "Kannika" },
    { th: "กรรณิการ์", en: "Kannikar" },
    { th: "กรวรรณ", en: "Kornwan" },
    { th: "กรวิภา", en: "Kornwipha" },
    { th: "กรุณา", en: "Karuna" },
    { th: "กฤตยา", en: "Krittaya" },
    { th: "กวินทิพย์", en: "Kawinthip" },
    { th: "กัลยา", en: "Kanya" },
    { th: "กัลยาณี", en: "Kalyanee" },
    { th: "กิตติมา", en: "Kittima" },
    { th: "กิรติกา", en: "Kirtika" },
    { th: "กิ่งกาญจน์", en: "Kingkan" },
    { th: "กิ่งแก้ว", en: "Kingkaeo" },
    { th: "กุสุมา", en: "Kusuma" },
    { th: "ขจีพรรณ", en: "Khajeepan" },
    { th: "ขวัญจิรา", en: "Khwanjira" },
    { th: "ขวัญทิพย์", en: "Khwanthip" },
    { th: "ครองพร", en: "Khrongphon" },
    { th: "คะนึงนิตย์", en: "Khanuengnit" },
    { th: "จรรยา", en: "Chanya" },
    { th: "จรัญพร", en: "Charanphon" },
    { th: "จรูญพรรณ", en: "Charunphan" },
    { th: "จันทนา", en: "Chanthana" },
    { th: "จันทนิภา", en: "Chantnipa" },
    { th: "จันทร์เพ็ญ", en: "Chanphen" },
    { th: "จารีรัตน์", en: "Chareerat" },
    { th: "จารุณี", en: "Charunee" },
    { th: "จารุวรรณ", en: "Charuwan" },
    { th: "จิดาภา", en: "Jidapa" },
    { th: "จิตติมา", en: "Jittima" },
    { th: "จิตรลดา", en: "Chitlada" },
    { th: "จินดาพรรณ", en: "Jindaphan" },
    { th: "จินดารัตน์", en: "Jindarat" },
    { th: "จินตนา", en: "Chintana" },
    { th: "จินตพร", en: "Chintaporn" },
    { th: "จิรัชญา", en: "Jiratchaya" },
    { th: "จีรพรรณ", en: "Jeeraphan" },
    { th: "จุฑาทิพย์", en: "Chuthathip" },
    { th: "จุฑาภรณ์", en: "Chuthaphorn" },
    { th: "จุฑามณี", en: "Chuthamanee" },
    { th: "จุฑารัตน์", en: "Chutharat" },
    { th: "จุไรรัตน์", en: "Churairat" },
    { th: "ฉัตราภรณ์", en: "Chatraphon" },
    { th: "ชนิกานต์", en: "Chanikan" },
    { th: "ชมพูนุช", en: "Chompunut" },
    { th: "ชลธิชา", en: "Chonthicha" },
    { th: "ชลิตา", en: "Chalita" },
    { th: "ชาลินี", en: "Chalinee" },
    { th: "ชุติกาญจน์", en: "Chutikan" },
    { th: "ชุติมา", en: "Chutima" },
    { th: "ช่อทิพย์", en: "Chothip" },
    { th: "ฐิตาพร", en: "Thitaporn" },
    { th: "ฐิติรัตน์", en: "Thitirat" },
    { th: "ณัชชา", en: "Natcha" },
    { th: "ณัฏฐธิดา", en: "Natthathida" },
    { th: "ณัฐชา", en: "Natcha" },
    { th: "ณัฐฐา", en: "Nattha" },
    { th: "ณัฐวดี", en: "Nattawadee" },
    { th: "ณิชกานต์", en: "Nichakan" },
    { th: "ณิชา", en: "Nicha" },
    { th: "ดารณี", en: "Daranee" },
    { th: "ดารินทร์", en: "Darin" },
    { th: "ดาวเรือง", en: "Daoreuang" },
    { th: "ทัดดาว", en: "Thaddao" },
    { th: "ทิพปภา", en: "Thippapha" },
    { th: "ทิพย์รัตน์", en: "Thipparat" },
    { th: "ธนพร", en: "Thanaporn" },
    { th: "ธนัญญา", en: "Thananya" },
    { th: "ธัญญา", en: "Thanya" },
    { th: "ธัญทิพย์", en: "Thanthip" },
    { th: "ธัญรัตน์", en: "Thanrat" },
    { th: "ธาริณี", en: "Tharinee" },
    { th: "ธิดารัตน์", en: "Thidarat" },
    { th: "นภา", en: "Napa" },
    { th: "นภาพร", en: "Napaporn" },
    { th: "นฤมล", en: "Naruemon" },
    { th: "นันทนา", en: "Nanthana" },
    { th: "นันทิกานต์", en: "Nanthikan" },
    { th: "นันทิชา", en: "Nanthicha" },
    { th: "นิชา", en: "Nicha" },
    { th: "นิชาภา", en: "Nichapa" },
    { th: "บุณยนุช", en: "Boonyanut" },
    { th: "บุญยพร", en: "Boonyaporn" },
    { th: "บุษบา", en: "Butsaba" },
    { th: "ปนัดดา", en: "Panadda" },
    { th: "ปรียา", en: "Preeya" },
    { th: "ปรียาดา", en: "Preeyada" },
    { th: "ปรียานุช", en: "Preeyanuch" },
    { th: "ปัทมา", en: "Pathama" },
    { th: "ปาริฉัตร", en: "Parichat" },
    { th: "ปิยนุช", en: "Piyanuch" },
    { th: "ปิยะวรรณ", en: "Piyawan" },
    { th: "พรรณทิพย์", en: "Phanthip" },
    { th: "พรพรรณ", en: "Phornphan" },
    { th: "พัชรมัย", en: "Patcharamai" },
    { th: "พิมพ์พรรณ", en: "Phimphan" },
    { th: "ภัทรลดา", en: "Phatlada" },
    { th: "ภัทรวรรณ", en: "Phatthrawan" },
    { th: "ภารวี", en: "Pharawi" },
    { th: "ภาวินี", en: "Phawinee" },
    { th: "มณีรัตน์", en: "Maneerat" },
    { th: "มัลลิกา", en: "Mallika" },
    { th: "มาลินี", en: "Malee" },
    { th: "มินตรา", en: "Mintra" },
    { th: "ยุพา", en: "Yupa" },
    { th: "รติมา", en: "Ratima" },
    { th: "รัชนี", en: "Ratchanee" },
    { th: "รัตนประภา", en: "Rattanaprapha" },
    { th: "รุจยา", en: "Rujaya" },
    { th: "รุจิราพร", en: "Rujiraporn" },
    { th: "ลดามณี", en: "Ladamanee" },
    { th: "วรกานต์", en: "Worakan" },
    { th: "วรรณพร", en: "Wanphon" },
    { th: "วราภรณ์", en: "Waraphorn" },
    { th: "วลัยพร", en: "Walaiphorn" },
    { th: "วลัยพรรณ", en: "Walaiphan" },
    { th: "วัชราภรณ์", en: "Watcharaphorn" },
    { th: "ศศิประภา", en: "Sasiprapha" },
    { th: "ศศิวิมล", en: "Sasiwimon" },
    { th: "ศิรินาถ", en: "Sirinat" },
    { th: "สกุณา", en: "Sakuna" },
    { th: "สุธิตา", en: "Suthita" },
    { th: "สุวรรณา", en: "Suwanna" },
    { th: "อรณี", en: "Aranee" },
    { th: "อรพรรณ", en: "Araphan" },
    { th: "อารยา", en: "Araya" },
    { th: "อินทิรา", en: "Inthira" },
    { th: "เกศรินทร์", en: "Ketsarin" },
    { th: "เพ็ญนภา", en: "Phennapha" },
    { th: "เรณู", en: "Renu" },
    { th: "โสภิตา", en: "Sophita" },
  ],
  femaleNicknames: [
    { th: "กิ๊บ", en: "Kip" },
    { th: "กิ๊ปซี่", en: "Kipsy" },
    { th: "แก้ว", en: "Kaeo" },
    { th: "กระแต", en: "Kratae" },
    { th: "กระต่าย", en: "Kratay" },
    { th: "กิฟท์", en: "Gift" },
    { th: "เกศ", en: "Ket" },
    { th: "ข้าว", en: "Khao" },
    { th: "ข้าวฟ่าง", en: "Khaofang" },
    { th: "เข็ม", en: "Khem" },
    { th: "ขวัญ", en: "Khwan" },
    { th: "คิม", en: "Kim" },
    { th: "แจ๋ว", en: "Jaeo" },
    { th: "จอย", en: "Joy" },
    { th: "จุ๊บแจง", en: "Chupjaeng" },
    { th: "เจน", en: "Jane" },
    { th: "จิน", en: "Jin" },
    { th: "แจน", en: "Jan" },
    { th: "จูน", en: "June" },
    { th: "ชะเอม", en: "Cha-em" },
    { th: "เชอร์รี่", en: "Cherry" },
    { th: "ดาว", en: "Dao" },
    { th: "ดรีม", en: "Dream" },
    { th: "เดือน", en: "Duean" },
    { th: "เตย", en: "Toey" },
    { th: "ตูน", en: "Toon" },
    { th: "แตน", en: "Taen" },
    { th: "แตงกวา", en: "Taengkwa" },
    { th: "เต้ย", en: "Toey" },
    { th: "ทิพย์", en: "Thip" },
    { th: "นา", en: "Na" },
    { th: "นุช", en: "Nuch" },
    { th: "น้ำ", en: "Nam" },
    { th: "เนม", en: "Name" },
    { th: "นุ่ม", en: "Num" },
    { th: "นก", en: "Nok" },
    { th: "บี๋", en: "Bee" },
    { th: "โบว์", en: "Bow" },
    { th: "เบลล์", en: "Bell" },
    { th: "ปลา", en: "Pla" },
    { th: "ปาหนัน", en: "Panan" },
    { th: "ปู", en: "Pu" },
    { th: "ปอนด์", en: "Pond" },
    { th: "แป้ง", en: "Pang" },
    { th: "แป้น", en: "Paen" },
    { th: "ปุ๊กปิ๊ก", en: "Pukpik" },
    { th: "ปุยฝ้าย", en: "Puifai" },
    { th: "ผกา", en: "Phaka" },
    { th: "ฝ้าย", en: "Fai" },
    { th: "พลอย", en: "Ploi" },
    { th: "แพร", en: "แพร" },
    { th: "แพท", en: "Pat" },
    { th: "พราว", en: "Phrao" },
    { th: "พิม", en: "Phim" },
    { th: "พิน", en: "Pin" },
    { th: "ฟ้า", en: "Fah" },
    { th: "เฟย์", en: "Faye" },
    { th: "ฟาง", en: "Fang" },
    { th: "มุก", en: "Muk" },
    { th: "มินท์", en: "Mint" },
    { th: "มีมี่", en: "Mimi" },
    { th: "โม", en: "Mo" },
    { th: "มิว", en: "Mew" },
    { th: "มะลิ", en: "Mali" },
    { th: "เมย์", en: "May" },
    { th: "มะปราง", en: "Maprang" },
    { th: "มนต์", en: "Mon" },
    { th: "แยม", en: "Yam" },
    { th: "มายด์", en: "Mind" },
    { th: "มด", en: "Mot" },
    { th: "ลูกหมี", en: "Lookmee" },
    { th: "ลูกแก้ว", en: "Lookkaeo" },
    { th: "แวว", en: "Waeo" },
    { th: "วิว", en: "View" },
    { th: "ส้ม", en: "Som" },
    { th: "ส้มโอ", en: "Som-o" },
    { th: "สีรุ้ง", en: "Seerung" },
    { th: "หวาน", en: "Wan" },
    { th: "เหมียว", en: "Meow" },
    { th: "หญิง", en: "Ying" },
    { th: "หลิว", en: "Liew" },
    { th: "หมิง", en: "Ming" },
    { th: "แอน", en: "Ann" },
    { th: "แอนนา", en: "Anna" },
    { th: "เอม", en: "Aim" },
    { th: "ออย", en: "Oi" },
    { th: "อีฟ", en: "Eve" },
    { th: "เอย", en: "Aei" },
    { th: "ไอซ์", en: "Ice" },
    { th: "ไอริณ", en: "Airin" },
  ],
  lastNames: [
    { th: "กติยา", en: "Katiya" },
    { th: "กมลานันท์", en: "Kamalanan" },
    { th: "กาญจนวิภู", en: "Kanchanawiphu" },
    { th: "กำธรเจริญ", en: "Kamthorncharoen" },
    { th: "กิจจานุรักษ์", en: "Kitchanurak" },
    { th: "กิตติธร", en: "Kittithon" },
    { th: "ครองจินดา", en: "Khrongchinda" },
    { th: "งามระลึก", en: "Ngamraluek" },
    { th: "จันทร์ประดับ", en: "Chanpradap" },
    { th: "จิตประสงค์", en: "Chitprasong" },
    { th: "จิตมานะ", en: "Chitmana" },
    { th: "จิตสะอาด", en: "Chitsa-at" },
    { th: "จิรามณี", en: "Chiramanee" },
    { th: "จุฑาเทพ", en: "Chuthatep" },
    { th: "ดำรงลาวรรณ", en: "Damronglawan" },
    { th: "ดิเรกวิทยา", en: "Direkwittaya" },
    { th: "ทองดี", en: "Thongdee" },
    { th: "ทองม่วง", en: "Thongmuang" },
    { th: "นทีพิทักษ์", en: "Natheepitak" },
    { th: "นิมิตนาม", en: "Nimitnam" },
    { th: "บุญมั่น", en: "Boonman" },
    { th: "ประจัญบาน", en: "Prachanban" },
    { th: "ประภาพร", en: "Praphaphon" },
    { th: "พงศ์พิทักษ์", en: "Phongphitak" },
    { th: "พจน์จำเนียร", en: "Photchamnian" },
    { th: "พรรณาราย", en: "Phannarai" },
    { th: "พิชัยรณรงค์", en: "Phichaironnarong" },
    { th: "พิทักษ์ไทย", en: "Phithakthai" },
    { th: "พึ่งสุข", en: "Phuengsuk" },
    { th: "พุ่มฉัตร", en: "Phumchat" },
    { th: "มณีน้อย", en: "Maneenoi" },
    { th: "มนูญศักดิ์", en: "Manunsak" },
    { th: "มหานิยม", en: "Mahanityom" },
    { th: "ยอดยาใจ", en: "Yodyajai" },
    { th: "รอดคงรวย", en: "Rotkhongruai" },
    { th: "รักธรรม", en: "Raktham" },
    { th: "รักสำราญ", en: "Raksamran" },
    { th: "รัตนามิรา", en: "Rattanamira" },
    { th: "รัตนเดชากร", en: "Rattanadechakorn" },
    { th: "รุจิอาภรณ์", en: "Ruchi-aphorn" },
    { th: "วงศ์บันเทิง", en: "Wongbanthoeng" },
    { th: "วงศ์สินวิเศษ", en: "Wongsinwiset" },
    { th: "วรรณดำรง", en: "Wannadamrong" },
    { th: "วรเลิศรัตน์", en: "Woralertrat" },
    { th: "วังชัยศรี", en: "Wangchaisri" },
    { th: "วาทะศรัทธา", en: "Wathasaraddha" },
    { th: "วิทยเขตปภา", en: "Wittayakhetphapha" },
    { th: "วิไลสักดิ์", en: "Wilaisak" },
    { th: "ศรีเจริญ", en: "Sricharoen" },
    { th: "ศิลามหาฤกษ์", en: "Silamaharuek" },
    { th: "ศิวาวงศ์", en: "Siwawong" },
    { th: "สมคำนึง", en: "Somkhamnueng" },
    { th: "สมุทรเทวา", en: "Samutthewa" },
    { th: "สันตติวงศ์", en: "Santatiwong" },
    { th: "สันต์สิริศักดิ์", en: "Sunsirisak" },
    { th: "สัมพันธ์พงษ์", en: "Samphanphong" },
    { th: "สำราญฤทธิ์", en: "Samranrit" },
    { th: "สุรบดินทร์", en: "Surabordin" },
    { th: "หงส์แก้ว", en: "Hongkaeo" },
    { th: "อัศวรัช", en: "Assawarat" },
    { th: "อัศวเรืองฤทธิ์", en: "Assawarueangrit" },
    { th: "อาจฤทธิ์", en: "Art-rit" },
    { th: "เกตุอารี", en: "Ket-aree" },
    { th: "เกิดความสุข", en: "Kerdkhwamsuk" },
    { th: "เกิดงามพริ้ง", en: "Kerdngamphring" },
    { th: "เจนพานิชย์สกุล", en: "Jenphanitsakun" },
    { th: "เจริญเดช", en: "Charoendet" },
    { th: "เทพทัต", en: "Thephathat" },
    { th: "เทพสุวรรณ", en: "Thepsuwan" },
    { th: "เที่ยงธรรม", en: "Thiangtham" },
    { th: "เหนือกาล", en: "Nueakan" },
    { th: "แก้วมณีงาม", en: "Kaeomaningam" },
    { th: "แสนชล", en: "Saenchon" },
    { th: "โชคช่วย", en: "Chokchuai" },
    { th: "ไชยวัฒนา", en: "Chaiwattana" },
    { th: "อนุรักษ์ชัย", en: "Anurakchai" },
    { th: "ปณิธาน", en: "Panithan" },
    { th: "วิจิตรนาวา", en: "Wijitnawa" },
    { th: "นลินีภัทร", en: "Nalineepat" },
    { th: "ปุณยวัจน์", en: "Punyawat" },
    { th: "ฐิติรัตน์", en: "Thitirat" },
    { th: "จารุวรรณ", en: "Charuwan" },
    { th: "ชาญชัย", en: "Charnchai" },
    { th: "สุพรรณิการ์", en: "Suphannika" },
  ],
};
