/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BlogImport } from './routes/blog'
import { Route as IndexImport } from './routes/index'
import { Route as ToolsCalculatorsTdeeIndexImport } from './routes/tools/calculators/tdee/index'
import { Route as ToolsCalculatorsBmrIndexImport } from './routes/tools/calculators/bmr/index'
import { Route as ToolsCalculatorsBmiIndexImport } from './routes/tools/calculators/bmi/index'

// Create/Update Routes

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsTdeeIndexRoute = ToolsCalculatorsTdeeIndexImport.update({
  id: '/tools/calculators/tdee/',
  path: '/tools/calculators/tdee/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsBmrIndexRoute = ToolsCalculatorsBmrIndexImport.update({
  id: '/tools/calculators/bmr/',
  path: '/tools/calculators/bmr/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorsBmiIndexRoute = ToolsCalculatorsBmiIndexImport.update({
  id: '/tools/calculators/bmi/',
  path: '/tools/calculators/bmi/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/bmi/': {
      id: '/tools/calculators/bmi/'
      path: '/tools/calculators/bmi'
      fullPath: '/tools/calculators/bmi'
      preLoaderRoute: typeof ToolsCalculatorsBmiIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/bmr/': {
      id: '/tools/calculators/bmr/'
      path: '/tools/calculators/bmr'
      fullPath: '/tools/calculators/bmr'
      preLoaderRoute: typeof ToolsCalculatorsBmrIndexImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculators/tdee/': {
      id: '/tools/calculators/tdee/'
      path: '/tools/calculators/tdee'
      fullPath: '/tools/calculators/tdee'
      preLoaderRoute: typeof ToolsCalculatorsTdeeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/tools/calculators/bmi': typeof ToolsCalculatorsBmiIndexRoute
  '/tools/calculators/bmr': typeof ToolsCalculatorsBmrIndexRoute
  '/tools/calculators/tdee': typeof ToolsCalculatorsTdeeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/tools/calculators/bmi': typeof ToolsCalculatorsBmiIndexRoute
  '/tools/calculators/bmr': typeof ToolsCalculatorsBmrIndexRoute
  '/tools/calculators/tdee': typeof ToolsCalculatorsTdeeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/tools/calculators/bmi/': typeof ToolsCalculatorsBmiIndexRoute
  '/tools/calculators/bmr/': typeof ToolsCalculatorsBmrIndexRoute
  '/tools/calculators/tdee/': typeof ToolsCalculatorsTdeeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/tools/calculators/bmi'
    | '/tools/calculators/bmr'
    | '/tools/calculators/tdee'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/tools/calculators/bmi'
    | '/tools/calculators/bmr'
    | '/tools/calculators/tdee'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/tools/calculators/bmi/'
    | '/tools/calculators/bmr/'
    | '/tools/calculators/tdee/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ToolsCalculatorsBmiIndexRoute: typeof ToolsCalculatorsBmiIndexRoute
  ToolsCalculatorsBmrIndexRoute: typeof ToolsCalculatorsBmrIndexRoute
  ToolsCalculatorsTdeeIndexRoute: typeof ToolsCalculatorsTdeeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ToolsCalculatorsBmiIndexRoute: ToolsCalculatorsBmiIndexRoute,
  ToolsCalculatorsBmrIndexRoute: ToolsCalculatorsBmrIndexRoute,
  ToolsCalculatorsTdeeIndexRoute: ToolsCalculatorsTdeeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/tools/calculators/bmi/",
        "/tools/calculators/bmr/",
        "/tools/calculators/tdee/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx"
    },
    "/tools/calculators/bmi/": {
      "filePath": "tools/calculators/bmi/index.tsx"
    },
    "/tools/calculators/bmr/": {
      "filePath": "tools/calculators/bmr/index.tsx"
    },
    "/tools/calculators/tdee/": {
      "filePath": "tools/calculators/tdee/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
