/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BlogImport } from './routes/blog'
import { Route as IndexImport } from './routes/index'
import { Route as ToolsCalculatorIndexImport } from './routes/tools.calculator.index'
import { Route as ToolsCalculatorBmiImport } from './routes/tools.calculator.bmi'

// Create/Update Routes

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorIndexRoute = ToolsCalculatorIndexImport.update({
  id: '/tools/calculator/',
  path: '/tools/calculator/',
  getParentRoute: () => rootRoute,
} as any)

const ToolsCalculatorBmiRoute = ToolsCalculatorBmiImport.update({
  id: '/tools/calculator/bmi',
  path: '/tools/calculator/bmi',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculator/bmi': {
      id: '/tools/calculator/bmi'
      path: '/tools/calculator/bmi'
      fullPath: '/tools/calculator/bmi'
      preLoaderRoute: typeof ToolsCalculatorBmiImport
      parentRoute: typeof rootRoute
    }
    '/tools/calculator/': {
      id: '/tools/calculator/'
      path: '/tools/calculator'
      fullPath: '/tools/calculator'
      preLoaderRoute: typeof ToolsCalculatorIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/tools/calculator/bmi': typeof ToolsCalculatorBmiRoute
  '/tools/calculator': typeof ToolsCalculatorIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/tools/calculator/bmi': typeof ToolsCalculatorBmiRoute
  '/tools/calculator': typeof ToolsCalculatorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/tools/calculator/bmi': typeof ToolsCalculatorBmiRoute
  '/tools/calculator/': typeof ToolsCalculatorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/tools/calculator/bmi' | '/tools/calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/tools/calculator/bmi' | '/tools/calculator'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/tools/calculator/bmi'
    | '/tools/calculator/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ToolsCalculatorBmiRoute: typeof ToolsCalculatorBmiRoute
  ToolsCalculatorIndexRoute: typeof ToolsCalculatorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ToolsCalculatorBmiRoute: ToolsCalculatorBmiRoute,
  ToolsCalculatorIndexRoute: ToolsCalculatorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog",
        "/tools/calculator/bmi",
        "/tools/calculator/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blog": {
      "filePath": "blog.tsx"
    },
    "/tools/calculator/bmi": {
      "filePath": "tools.calculator.bmi.tsx"
    },
    "/tools/calculator/": {
      "filePath": "tools.calculator.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
